# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20170213_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
